// Phase: P0 (implemented)
// Menu: TW → Setup Project creates and assigns a URP asset. TW → Build Bootstrap Scenes generates
// Bootstrap.unity (loader) and GreyboxCorridor.unity (SimHost + camera + overlay + terrain view) and registers
// them in Build Settings. Scenes are generated by code so the skeleton needs no hand-written YAML.
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEngine.SceneManagement;
using TW.Presentation;
using TW.Presentation.Tactical;
using TW.Presentation.Terrain;

namespace TW.Editor
{
    public static class BootstrapSceneBuilder
    {
        const string ScenesDir = "Assets/_Project/Scenes";
        const string SettingsDir = "Assets/_Project/Settings";

        [MenuItem("TW/Setup Project (URP asset, quality)")]
        public static void SetupProject()
        {
            Directory.CreateDirectory(SettingsDir);
            var rendererData = ScriptableObject.CreateInstance<UniversalRendererData>();
            AssetDatabase.CreateAsset(rendererData, $"{SettingsDir}/TW-Renderer.asset");
            var pipeline = UniversalRenderPipelineAsset.Create(rendererData);
            pipeline.supportsCameraDepthTexture = true;
            pipeline.msaaSampleCount = 1;
            pipeline.shadowDistance = 220f;
            AssetDatabase.CreateAsset(pipeline, $"{SettingsDir}/TW-URP.asset");
            GraphicsSettings.defaultRenderPipeline = pipeline;
            QualitySettings.renderPipeline = pipeline;
            AssetDatabase.SaveAssets();
            Debug.Log("TW: URP asset created and assigned. Set Project Settings → Player → Active Input Handling to 'Input System Package' or 'Both' if not already.");
        }

        [MenuItem("TW/Build Bootstrap Scenes")]
        public static void BuildScenes()
        {
            Directory.CreateDirectory(ScenesDir);
            string greybox = BuildGreybox();
            string bootstrap = BuildBootstrap();
            EditorBuildSettings.scenes = new[]
            {
                new EditorBuildSettingsScene(bootstrap, true),
                new EditorBuildSettingsScene(greybox, true),
            };
            EditorSceneManager.OpenScene(greybox);
            Debug.Log("TW: scenes built. Press Play in GreyboxCorridor.");
        }

        static string BuildGreybox()
        {
            var scene = EditorSceneManager.NewScene(NewSceneSetup.DefaultGameObjects, NewSceneMode.Single);
            var host = new GameObject("SimHost").AddComponent<SimHost>();
            host.StressUnits = 0;

            var cam = Camera.main;
            cam.gameObject.AddComponent<TacticalCamera>().Host = host;
            cam.farClipPlane = 1500f;
            var overlay = cam.gameObject.AddComponent<DebugOverlay>();
            overlay.Host = host;

            var terrain = new GameObject("GreyboxTerrain");
            terrain.AddComponent<MeshFilter>();
            terrain.AddComponent<MeshRenderer>();
            terrain.AddComponent<GreyboxTerrainView>().Host = host;

            var light = Object.FindFirstObjectByType<Light>();
            if (light != null) { light.transform.rotation = Quaternion.Euler(50f, -30f, 0f); light.shadows = LightShadows.Soft; }

            string path = $"{ScenesDir}/GreyboxCorridor.unity";
            EditorSceneManager.SaveScene(scene, path);
            return path;
        }

        static string BuildBootstrap()
        {
            var scene = EditorSceneManager.NewScene(NewSceneSetup.DefaultGameObjects, NewSceneMode.Single);
            new GameObject("Bootstrap").AddComponent<BootstrapLoader>().SceneName = "GreyboxCorridor";
            string path = $"{ScenesDir}/Bootstrap.unity";
            EditorSceneManager.SaveScene(scene, path);
            return path;
        }
    }
}
