// Phase: P0 (implemented)
// Batch: Unity.exe -batchmode -executeMethod TW.Editor.BootstrapSceneBuilder.SetupAll
// Menu: TW → Setup Project creates and assigns a URP asset. TW → Build Bootstrap Scenes generates
// Bootstrap.unity (loader) and GreyboxCorridor.unity (SimHost + camera + overlay + terrain view) and registers
// them in Build Settings. Scenes are generated by code so the skeleton needs no hand-written YAML.
//
// The settings and scenes are committed and have been tuned since (the renderer's InkLines feature, the battle
// scene, MainMenu in Build Settings). Running the steps over them replaces that work, so SetupAll only runs a step
// whose output is missing, and the menu items ask before replacing a file that exists.
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEngine.SceneManagement;
using TW.Presentation;
using TW.Presentation.Tactical;
using TW.Presentation.Terrain;

namespace TW.Editor
{
    public static class BootstrapSceneBuilder
    {
        const string ScenesDir = "Assets/_Project/Scenes";
        const string SettingsDir = "Assets/_Project/Settings";

        [MenuItem("TW/Setup Project (URP asset, quality)")]
        static void SetupProjectMenu()
        {
            if (!File.Exists(UrpAsset) || EditorUtility.DisplayDialog("Replace the URP asset?",
                    "TW-URP.asset and TW-Renderer.asset are committed and tuned. Replace them with fresh defaults?", "Replace", "Cancel"))
                SetupProject();
        }

        const string UrpAsset = SettingsDir + "/TW-URP.asset";
        static readonly string[] Scenes = { ScenesDir + "/GreyboxCorridor.unity", ScenesDir + "/Bootstrap.unity" };

        public static void SetupProject()
        {
            Directory.CreateDirectory(SettingsDir);
            var rendererData = ScriptableObject.CreateInstance<UniversalRendererData>();
            AssetDatabase.CreateAsset(rendererData, $"{SettingsDir}/TW-Renderer.asset");
            var pipeline = UniversalRenderPipelineAsset.Create(rendererData);
            pipeline.supportsCameraDepthTexture = true;
            pipeline.msaaSampleCount = 1;
            pipeline.shadowDistance = 220f;
            AssetDatabase.CreateAsset(pipeline, $"{SettingsDir}/TW-URP.asset");
            GraphicsSettings.defaultRenderPipeline = pipeline;
            QualitySettings.renderPipeline = pipeline;
            AssetDatabase.SaveAssets();
            Debug.Log("TW: URP asset created and assigned.");
        }

        /// <summary>The steps SetupAll would run on this checkout: only those whose output is missing. On a clone of the
        /// repo it is none but the input-handling check, which changes nothing when it is already set.</summary>
        public static string[] StepsSetupAllWouldRun()
        {
            var steps = new System.Collections.Generic.List<string>();
            if (!File.Exists(UrpAsset)) steps.Add(nameof(SetupProject));
            steps.Add(nameof(SetActiveInputHandling));
            if (!System.Array.TrueForAll(Scenes, File.Exists)) steps.Add(nameof(BuildScenes));
            return steps.ToArray();
        }

        /// <summary>What a checkout without the committed settings or scenes needs, in order. Batch-mode entry point.</summary>
        public static void SetupAll()
        {
            var steps = StepsSetupAllWouldRun();
            if (System.Array.IndexOf(steps, nameof(SetupProject)) >= 0) SetupProject(); else Debug.Log("TW: URP asset kept (committed).");
            SetActiveInputHandling();
            if (System.Array.IndexOf(steps, nameof(BuildScenes)) >= 0) BuildScenes(); else Debug.Log("TW: scenes kept (committed).");
        }

        [MenuItem("TW/Setup Input Handling (Input System Package)")]
        public static void SetActiveInputHandling()
        {
            // TacticalCamera/DebugOverlay read Keyboard.current / Mouse.current, which are null under the legacy Input Manager.
            var assets = AssetDatabase.LoadAllAssetsAtPath("ProjectSettings/ProjectSettings.asset");
            if (assets == null || assets.Length == 0) { Debug.LogWarning("TW: ProjectSettings.asset not found; set Active Input Handling by hand."); return; }
            var so = new SerializedObject(assets[0]);
            var prop = so.FindProperty("activeInputHandler");
            if (prop == null) { Debug.LogWarning("TW: activeInputHandler not found; set Active Input Handling by hand."); return; }
            const int InputSystemPackage = 1; // 0 = Input Manager (Old), 1 = Input System Package (New), 2 = Both
            if (prop.intValue == InputSystemPackage) return;
            prop.intValue = InputSystemPackage;
            so.ApplyModifiedPropertiesWithoutUndo();
            AssetDatabase.SaveAssets();
            Debug.Log("TW: Active Input Handling set to Input System Package. Restart the editor if it was open.");
        }

        [MenuItem("TW/Build Bootstrap Scenes")]
        static void BuildScenesMenu()
        {
            if (!System.Array.Exists(Scenes, File.Exists) || EditorUtility.DisplayDialog("Regenerate the scenes?",
                    "GreyboxCorridor.unity and Bootstrap.unity are committed and edited by hand since. Regenerate them, and reset "
                    + "Build Settings to those two (MainMenu drops out)?", "Regenerate", "Cancel"))
                BuildScenes();
        }

        public static void BuildScenes()
        {
            Directory.CreateDirectory(ScenesDir);
            string greybox = BuildGreybox();
            string bootstrap = BuildBootstrap();
            EditorBuildSettings.scenes = new[]
            {
                new EditorBuildSettingsScene(bootstrap, true),
                new EditorBuildSettingsScene(greybox, true),
            };
            EditorSceneManager.OpenScene(greybox);
            Debug.Log("TW: scenes built. Press Play in GreyboxCorridor.");
        }

        static string BuildGreybox()
        {
            var scene = EditorSceneManager.NewScene(NewSceneSetup.DefaultGameObjects, NewSceneMode.Single);
            var host = new GameObject("SimHost").AddComponent<SimHost>();
            host.StressUnits = 0;

            var cam = Camera.main;
            cam.gameObject.AddComponent<TacticalCamera>().Host = host;
            cam.farClipPlane = 1500f;
            var overlay = cam.gameObject.AddComponent<DebugOverlay>();
            overlay.Host = host;
            cam.gameObject.AddComponent<CombatFx>().Host = host;
            cam.gameObject.AddComponent<BattleHud>().Host = host;
            var panel = cam.gameObject.AddComponent<TestPanel>();
            panel.Host = host;
            panel.Cam = cam.GetComponent<TacticalCamera>();

            var terrain = new GameObject("GreyboxTerrain");
            terrain.AddComponent<MeshFilter>();
            terrain.AddComponent<MeshRenderer>();
            terrain.AddComponent<GreyboxTerrainView>().Host = host;

            var light = Object.FindFirstObjectByType<Light>();
            if (light != null) { light.transform.rotation = Quaternion.Euler(50f, -30f, 0f); light.shadows = LightShadows.Soft; }

            string path = $"{ScenesDir}/GreyboxCorridor.unity";
            EditorSceneManager.SaveScene(scene, path);
            return path;
        }

        static string BuildBootstrap()
        {
            var scene = EditorSceneManager.NewScene(NewSceneSetup.DefaultGameObjects, NewSceneMode.Single);
            new GameObject("Bootstrap").AddComponent<BootstrapLoader>().SceneName = "GreyboxCorridor";
            string path = $"{ScenesDir}/Bootstrap.unity";
            EditorSceneManager.SaveScene(scene, path);
            return path;
        }
    }
}
