# The flamethrower's books, cut from the owner's generated flipbook pack (G:/My Drive/vfx, ComfyUI + Minimax H3 in the
# style of the DucVu 2D explosion pack). Every book in Resources/VFX is a GREYSCALE drawing with alpha, because
# TW/Flipbook reads the drawing's value (ink = luma(rgb)/alpha) and colours it itself from _Tint, _Levels and the scene,
# so a cloud sits under the same moon as the men. The colour is thrown away here and kept only as value.
#
# Which means the pack's PALETTE IS IRRELEVANT: a blue sheet is not a blue effect, it is a different DRAWING. The pack
# draws in five palettes and the first round only took the orange ones - and so faked a jet out of a chain of round
# fireballs while blue_direction_explosion, a stream drawn rooted at its left edge, sat unused. This round takes the
# drawings the fire actually needs, whatever colour they came in.
#
# Two ways to read value, and the choice is not cosmetic. LUMA reads colour TEMPERATURE as brightness, which is exactly
# right for the orange sheets: a white heart comes out 1.0, mid orange 0.6, the deep red fringe 0.25. It is wrong for a
# saturated blue or green - pure blue's luma is 0.11, so the brightest part of the blue stream would come out darker
# than an orange fringe.
#
# The obvious fix, the max channel (HSV value), is worse. A saturated hue ramp pins its max channel at 1.0 as soon as
# the hue is present, so a drawing shaded from deep blue to pale blue reads as flat white: measured on
# blue_direction, 39% of the drawing lands in the shader's top cel band under max, against 27% for FireBall under luma,
# and the stream rendered as one cream slab with the drawing lost inside it.
#
# LIGHTNESS, (max + min) / 2, is what those books use instead. It tracks how much white the artist mixed into the hue,
# which IS the shading, and it leaves 12% in the top band - the drawing survives. The orange books keep luma (they are
# already tuned, and are regenerated byte-identical - checked below).
#
# usage:  python firebooks.py [packdir] [outdir]
import os, sys, hashlib
import numpy as np
from PIL import Image

PACK = sys.argv[1] if len(sys.argv) > 1 else "G:/My Drive/vfx/sheets"
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "..", "Assets", "_Project", "Resources", "VFX")
CELL = 256          # cell edge out (the pack draws 320); 8x4 lands on a 2048x1024 texture
COLS, ROWS = 8, 4
ALPHA_FLOOR = 6     # alpha this low is the keyer's haze, not drawing: it only makes the mips grey

# name -> (pack file, mode, root-left, keep)
#   mode:      "luma" for the orange sheets, "light" for saturated blue/green/red ones (see above)
#   root-left: slide every cell so the drawing's root sits on x = 0 (directional books: Mirror flips left/right, so a
#              rooted book has to have its root on the edge, the way Muzzle does)
#   keep:      (first, last) frame of the pack sheet to keep, inclusive; None = all. The dropped frames are a streak of
#              the shell arriving, or a fan that overflows its cell, or a tail that is a different drawing.
BOOKS = {
    "FireBall":   ("orange_fire_explosion_8x4_12fps_32f.png",      "luma", False, None),
    "FireColumn": ("orange_ground_explosion_8x4_12fps_30f.png",    "luma", False, None),
    "FireBurst":  ("orange_center_explode_8x4_12fps_32f.png",      "luma", False, None),
    "FireJet":    ("blue_direction_explosion_8x4_12fps_29f.png",   "light",  True,  None),      # the stream: start f0-11, hold f11-18, stop f19-28
    # The cook-off. This was orange_electric_explosion, and it was the wrong sheet from the beginning: measured over
    # its whole book its interior holes reach 40% of the filled silhouette, with one hole alone at 21.6%, so its tail is
    # an expanding ring rather than a fireball. Two rounds were spent cutting further and further into it (25, then 18,
    # then 11 frames) to stay ahead of the annulus, and each cut bought a cleaner silhouette by throwing away more of
    # the beat - until a tank going up rendered smaller and dimmer than a campfire burning behind it. purple_explosion
    # needs no cut at all. But hole area alone does NOT choose a fireball: purple_explosion scores a perfect 0.0% and
    # is a thin swooping ARC - an arc encloses nothing, so it cannot have a hole - and in game it drew a giant orange
    # comma standing over the wreck. Solidity, area against the bounding box, is the measure that separates them: 0.31
    # for that arc against 0.48 here and 0.55 for the annulus sheet. This one is the best of the pack on both at once,
    # 1.1% holes and 0.48 solid, with 0.81 filled through its own centroid. The whole book is usable.
    "FireBlast":  ("purple_fire_explosion_8x4_12fps_32f.png",      "light",  False, None),
    "FireFan":    ("green_direction_explosion_8x4_12fps_32f.png",  "light",  True,  (8, 23)),   # the splash where the jet lands
    "FireStand":  ("blue_fire_explosion_8x4_12fps_32f.png",        "light",  False, (2, 17)),   # a standing flame with a skirt (loops)
    "FirePool":   ("blood_ground_1_8x4_12fps_32f.png",             "light",  False, (16, 31)),  # a puddle with a blob rising off it
    # The stream's opaque CORE, and a second drawing of a stream so the chain is not one glyph stamped down its length.
    # Measured against blue_direction over the body frames: the same root discipline (left edge 0.06 vs 0.05, so it is
    # drawn rooted and can be laid from the nozzle) but a denser drawing - 0.26 cover against 0.22, and 0.30 roundness
    # against 0.18, which is to say fewer holes and a fuller body. That is what the inside of a pressurised stream is.
    "FireCore":   ("purple_direction_explosion_8x4_12fps_32f.png",  "light",  True,  (6, 27)),
    # The stream's TERMINUS. A jet that simply stops has no last beat: the fire has to turn a corner and go up. This is
    # a ground explosion, which is the right drawing for that - measured, its ink reaches 0.94 of the way down its cell
    # (so it is rooted on the floor and can stand on the ground the stream ends over) and it is the densest of the
    # pack's ground sheets at 0.32 cover. Frames 4-24: after the arrival flash, through the bloom and its first fall.
    "FireBloom":  ("blue_ground_explosion_8x4_12fps_27f.png",       "light",  False, (4, 24)),
    # The jet's HEAD. The stream books are drawn as curls, and a curl has a hole through the middle of it - which is
    # invisible on a link buried in a chain and fatal on the leading mass, where clean terrain read straight through
    # the centre of the hottest object in the shot. Measured over the body frames, this one is 0.91 solid through its
    # own centroid against 0.65-0.72 for most of the pack: a closed bolus, which is what the head of a gout of burning
    # fuel is. It is an explosion sheet and it is used here for one card only.
    "FireHead":   ("orange_explosion_8x4_12fps_26f.png",            "luma",   False, (4, 22)),
}
FRAMES_IN = {"FireBall": 32, "FireColumn": 30, "FireBurst": 32, "FireJet": 29, "FireBlast": 32, "FireFan": 32, "FireStand": 32, "FirePool": 32, "FireCore": 32, "FireBloom": 27, "FireHead": 26}
# FireBall's band split, measured in round 2: the shader's default _Bands and the levels its Sheet row uses
FIREBALL_BANDS = (0.12, 0.40, 0.86)
FIREBALL_LEVELS = (0.16, 0.86)


def cells(a, cols, rows):
    h, w = a.shape[0] // rows, a.shape[1] // cols
    return [a[r * h:(r + 1) * h, c * w:(c + 1) * w] for r in range(rows) for c in range(cols)], h, w


def root_crop(cs, w):
    """How much dead space stands to the left of the drawing across the frames: the root's x."""
    left = w
    for c in cs:
        m = c[..., 3] > 25
        if m.any():
            left = min(left, int(np.where(m.any(0))[0][0]))
    return max(0, left)


def value(rgb, mode):
    if mode == "luma":
        return (rgb[..., 0] * 0.299 + rgb[..., 1] * 0.587 + rgb[..., 2] * 0.114) / 255.0
    return (rgb.max(-1) + rgb.min(-1)) / 510.0   # lightness: how much white is in the hue, which is the shading


def shares(band, cuts):
    return [float((band < c).mean()) for c in cuts]


def convert(name, src, mode, rootleft, keep):
    a = np.array(Image.open(src).convert("RGBA")).astype(np.float32)
    cs, ch, cw = cells(a, COLS, ROWS)
    first, last = keep if keep else (0, FRAMES_IN[name] - 1)
    cs = cs[first:last + 1]
    cut = root_crop(cs, cw) if rootleft else 0
    out = Image.new("RGBA", (COLS * CELL, ROWS * CELL), (0, 0, 0, 0))
    xl, xr, yt, yb = 1.0, 0.0, 1.0, 0.0
    lines = []
    for i, cell in enumerate(cs):
        if cut:
            cell = np.concatenate([cell[:, cut:], np.zeros((ch, cut, 4), np.float32)], axis=1)
        al = cell[..., 3] / 255.0
        al[al < ALPHA_FLOOR / 255.0] = 0.0
        v = np.clip(value(cell[..., :3], mode), 0.0, 1.0)
        grey = np.clip(v * al * 255.0 + 0.5, 0, 255).astype(np.uint8)
        px = np.dstack([grey, grey, grey, np.clip(al * 255.0 + 0.5, 0, 255).astype(np.uint8)])
        im = Image.fromarray(px, "RGBA").resize((CELL, CELL), Image.LANCZOS)
        out.paste(im, ((i % COLS) * CELL, (i // COLS) * CELL))
        m = al > 0.1
        if m.any():
            ys, xs = np.nonzero(m)
            l, r, t, b = xs.min() / cw, xs.max() / cw, ys.min() / ch, ys.max() / ch
            xl, xr, yt, yb = min(xl, l), max(xr, r), min(yt, t), max(yb, b)
            lines.append(f"      f{first + i:2d}: cover {m.mean():.2f}  x {l:.2f}-{r:.2f}  y {t:.2f}-{b:.2f}")
    dst = os.path.join(OUT, name + ".png")
    out.save(dst)
    # the levels and bands the book actually uses, read back off the OUTPUT the way the shader will read them
    q = np.array(out).astype(np.float32)
    m = q[..., 3] > 20
    ink = q[..., 0][m] / np.maximum(q[..., 3][m], 16.0)
    low, high = float(np.percentile(ink, 3)), float(np.percentile(ink, 97))
    band = np.clip((ink - low) / max(0.01, high - low), 0, 1)
    print(f"{name:-<11s} {os.path.basename(src)}  mode {mode}  frames {len(cs)}  root cut {cut}px  cover {m.mean():.3f}")
    print(f"      ink p03 {low:.2f} p10 {np.percentile(ink, 10):.2f} p50 {np.percentile(ink, 50):.2f} p90 {np.percentile(ink, 90):.2f} p97 {high:.2f}")
    print(f"      extent  x {xl:.2f}-{xr:.2f} (fill {xr - xl:.2f})   y {yt:.2f}-{yb:.2f}  -> Ink=({1 - yb:.2f}, {1 - yt:.2f}) bottom-up")
    hist, _ = np.histogram(band, bins=20, range=(0, 1))
    print("      band histogram: " + " ".join(f"{h / len(band):.2f}" for h in hist))
    return dst, low, high, ink, band, lines


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    before = {n: hashlib.md5(open(os.path.join(OUT, n + ".png"), "rb").read()).hexdigest()
              for n in ("FireBall", "FireColumn", "FireBurst") if os.path.exists(os.path.join(OUT, n + ".png"))}
    ref_shares = None
    for name, (f, mode, root, keep) in BOOKS.items():
        dst, low, high, ink, band, lines = convert(name, os.path.join(PACK, f), mode, root, keep)
        if name == "FireBall":
            fb = np.clip((ink - FIREBALL_LEVELS[0]) / (FIREBALL_LEVELS[1] - FIREBALL_LEVELS[0]), 0, 1)
            ref_shares = shares(fb, FIREBALL_BANDS)
            print(f"      FireBall band shares under {FIREBALL_BANDS}: {[round(s, 2) for s in ref_shares]}")
        else:
            cuts = [float(np.quantile(band, s)) for s in ref_shares]
            print(f"      share-matched _Bands for this book: ({cuts[0]:.2f}, {cuts[1]:.2f}, {cuts[2]:.2f})   with Low {low:.2f} High {high:.2f}")
        if root or keep:
            print("\n".join(lines[:4] + ["      ..."] + lines[-3:]))
    after = {n: hashlib.md5(open(os.path.join(OUT, n + ".png"), "rb").read()).hexdigest() for n in before}
    for n in before:
        print(f"{'UNCHANGED' if before[n] == after[n] else '*** CHANGED ***'} {n}.png")
