#!/usr/bin/env python3
"""The index of the handoffs on the Drive: which one is current for a topic, and which a later one replaced.

    python Tools/handoffs.py                     the current handoffs, one line each, and what check finds
    python Tools/handoffs.py check               exit 1 when the index and the folder disagree (the rules are below)
    python Tools/handoffs.py new FILE --topic T --for "what it is for" [--replaces OLD]
    python Tools/handoffs.py replace OLD NEW     OLD is replaced by NEW (NEW is a listed handoff, or `repo:<path>`)
    python Tools/handoffs.py done FILE           the work it handed over is finished
    python Tools/handoffs.py park FILE           nobody works on it now, and it is still the newest word
    python Tools/handoffs.py render              write INDEX.md again from handoffs.json

WHY. A session hands work to the next one with a file `HANDOFF_AGENT_<topic>.md` in the Drive's TW3D-pipeline
folder, because that folder reaches both stations and a live message does not. On 2026-10-07 there were 20 of them
and no list: an agent found one by knowing its name, six still said "not landed" about a lane that had landed, and
nothing said which file a newer one had replaced. This tool keeps one list (`handoffs.json`, beside the handoffs)
and writes `INDEX.md` from it. A session that writes a handoff registers it with `new`; that is the whole habit.

What `check` refuses: a handoff file that is not listed; a listed file that is gone; two current handoffs on one
topic; a "replaced by" that names nothing; an INDEX.md that is not what `render` would write. It reads no handoff's
text: whether a sentence in one is still true is for its writer, and the state says how far to trust it.

The folder is TW_HANDOFFS, else the Drive's TW3D-pipeline. `health.py` prints one line from this ("not read" when the
Drive is not mounted here). Stdlib only.
"""
import argparse
import datetime
import json
import os
import sys
from pathlib import Path

DRIVE = Path('G:/My Drive/TW3D-pipeline')
STATES = ('current', 'parked', 'replaced', 'done')
PATTERN = 'HANDOFF_AGENT_*.md'
SAYS = {'current': 'Current: start here', 'parked': 'Parked: the newest word, nobody is on it',
        'replaced': 'Replaced: read the newer file', 'done': 'Done: kept for the record'}


def folder():
    return Path(os.environ['TW_HANDOFFS']) if os.environ.get('TW_HANDOFFS') else DRIVE


def read(where: Path):
    f = where / 'handoffs.json'
    if not f.exists():
        return {'handoffs': {}, 'plans': [], 'others': {}}
    d = json.loads(f.read_text(encoding='utf-8'))
    d.setdefault('handoffs', {}), d.setdefault('plans', []), d.setdefault('others', {})
    return d


def write(where: Path, d):
    (where / 'handoffs.json').write_text(json.dumps(d, indent=2, sort_keys=True, ensure_ascii=False) + '\n',
                                         encoding='utf-8', newline='\n')
    (where / 'INDEX.md').write_text(render(where, d), encoding='utf-8', newline='\n')


def on_disk(where: Path):
    return sorted(p.relative_to(where).as_posix() for p in where.rglob(PATTERN))


def changed(where: Path, name):
    try:
        return datetime.datetime.fromtimestamp((where / name).stat().st_mtime).strftime('%Y-%m-%d')
    except OSError:
        return 'gone'


def render(where: Path, d):
    h = d['handoffs']
    out = ['# TW3D-pipeline: the index', '',
           'Written by `python Tools/handoffs.py` from `handoffs.json`. Do not edit this file: use the tool',
           '(`new`, `replace`, `done`, `park`), or the next `render` loses the edit.', '',
           'A number that changes by the hour (the queue, the integration tip, the replay version) is not in here',
           'and should not be in a handoff either: name the command that prints it.', '']
    for state in STATES:
        rows = sorted((n for n in h if h[n]['state'] == state), key=lambda n: (h[n]['topic'], n))
        if not rows:
            continue
        out += [f'## {SAYS[state]}', '']
        if state == 'replaced':
            out += ['| Topic | File | Replaced by | Read this one |', '|---|---|---|---|']
            out += [f'| {h[n]["topic"]} | `{n}` | `{h[n].get("by", "")}` | `{newest(h, n)}` |' for n in rows]
        else:
            out += ['| Topic | File | Changed | What it is for |', '|---|---|---|---|']
            out += [f'| {h[n]["topic"]} | `{n}` | {changed(where, n)} | {h[n].get("for", "")} |' for n in rows]
        out.append('')
    if d['plans']:
        out += ['## Plans of record', '', '| Plan | Where | State |', '|---|---|---|']
        out += [f'| {p["what"]} | `{p["where"]}` | {p.get("state", "")} |' for p in d['plans']]
        out.append('')
    if d['others']:
        out += ['## The rest of this folder', '', '| Name | Holds |', '|---|---|']
        out += [f'| `{n}` | {d["others"][n]} |' for n in sorted(d['others'])]
        out.append('')
    return '\n'.join(out)


def newest(h, name):
    """Where a chain of replacements ends: the file to read. A chain that comes back on itself ends where it turns."""
    seen = [name]
    while h.get(name, {}).get('state') == 'replaced' and h[name].get('by') in h and h[name]['by'] not in seen:
        name = h[name]['by']
        seen.append(name)
    by = h.get(name, {}).get('by', '')
    return by if h.get(name, {}).get('state') == 'replaced' and by.startswith('repo:') else name


def problems(where: Path, d=None):
    d = d or read(where)
    h, out = d['handoffs'], []
    here = on_disk(where)
    out += [f'{n}: not in the index (python Tools/handoffs.py new {n} --topic ... --for "...")'
            for n in here if n not in h]
    out += [f'{n}: listed, and the file is gone' for n in sorted(h) if n not in here]
    topics = {}
    for n in sorted(h):
        if h[n].get('state') not in STATES:
            out.append(f'{n}: state {h[n].get("state")!r} is none of {", ".join(STATES)}')
        if h[n].get('state') == 'current':
            topics.setdefault(h[n]['topic'], []).append(n)
        if h[n].get('state') == 'replaced':
            by = h[n].get('by', '')
            if not by:
                out.append(f'{n}: replaced, and by nothing')
            elif not by.startswith('repo:') and by not in h:
                out.append(f'{n}: replaced by {by}, which is not a listed handoff (a doc in the repo is `repo:<path>`)')
            elif h.get(newest(h, n), {}).get('state') == 'replaced':
                out.append(f'{n}: its replacements come back on themselves and end on no file to read')
    out += [f'topic "{t}": {len(ns)} current handoffs ({", ".join(ns)}); one is current, replace the others'
            for t, ns in sorted(topics.items()) if len(ns) > 1]
    index = where / 'INDEX.md'
    if not index.exists() or index.read_text(encoding='utf-8') != render(where, d):
        out.append('INDEX.md is not what handoffs.json says (python Tools/handoffs.py render)')
    return out


def line(where: Path):
    """One line for health.py, and the problems under it."""
    d = read(where)
    n = {s: sum(1 for x in d['handoffs'].values() if x.get('state') == s) for s in STATES}
    bad = problems(where, d)
    head = (f'{n["current"]} current, {n["parked"]} parked, {n["replaced"] + n["done"]} replaced or done'
            f' ({where / "INDEX.md"})')
    return head + (f', {len(bad)} to mend' if bad else ''), bad


def need(d, name):
    if name not in d['handoffs']:
        raise SystemExit(f'handoffs: {name} is not in the index')
    return d['handoffs'][name]


def main(argv=None):
    ap = argparse.ArgumentParser(description='the index of the handoffs on the Drive')
    sub = ap.add_subparsers(dest='cmd')
    sub.add_parser('check')
    sub.add_parser('render')
    new = sub.add_parser('new')
    new.add_argument('file'), new.add_argument('--topic', required=True)
    new.add_argument('--for', dest='what', required=True), new.add_argument('--replaces')
    rep = sub.add_parser('replace')
    rep.add_argument('old'), rep.add_argument('new')
    for name in ('done', 'park'):
        sub.add_parser(name).add_argument('file')
    a = ap.parse_args(argv)
    where = folder()
    if not where.is_dir():
        print(f'handoffs: not read ({where} is not there)')
        return 1 if a.cmd else 0
    d = read(where)
    if a.cmd == 'new':
        if not (where / a.file).exists():
            raise SystemExit(f'handoffs: {where / a.file} does not exist: write the handoff first')
        d['handoffs'][a.file] = {'topic': a.topic, 'state': 'current', 'for': a.what}
        if a.replaces:
            need(d, a.replaces).update(state='replaced', by=a.file)
    elif a.cmd == 'replace':
        if not a.new.startswith('repo:'):
            need(d, a.new)
        need(d, a.old).update(state='replaced', by=a.new)
    elif a.cmd in ('done', 'park'):
        e = need(d, a.file)
        e['state'] = 'done' if a.cmd == 'done' else 'parked'
        e.pop('by', None)
    if a.cmd in ('new', 'replace', 'done', 'park', 'render'):
        write(where, d)
    bad = problems(where, d)
    if a.cmd in (None, 'check'):
        h = d['handoffs']
        for n in sorted((n for n in h if h[n]['state'] == 'current'), key=lambda n: h[n]['topic']):
            print(f'{h[n]["topic"]:<28} {n}')
            print(f'{"":<28} {h[n].get("for", "")}')
    for b in bad:
        print(f'MEND  {b}')
    if not bad and a.cmd:
        print(f'handoffs: {line(where)[0]}')
    return 1 if bad and a.cmd == 'check' else 0


if __name__ == '__main__':
    sys.exit(main())
