// Phase: C2 (ScriptableObject schemas implemented; assets generated by TW → Data → Create Slice Definitions)
// Authoring data. DataBaker turns these into the unmanaged stat structs the sim reads.
using System.Collections.Generic;
using UnityEngine;
using TW.Sim.Combat;
using TW.Sim.Match;
using TW.Sim.Units;

namespace TW.Data
{
    public enum Faction : byte { British = 0, German = 1, French = 2, UnitedStates = 3, Russian = 4, Italian = 5, AustroHungarian = 6, Ottoman = 7, Japanese = 8, Bulgarian = 9, Romanian = 10, Belgian = 11, Serbian = 12 }

    [CreateAssetMenu(menuName = "TW/Weapon Definition")]
    public sealed class WeaponDefinition : ScriptableObject
    {
        public short Id;
        public string DisplayName;
        public FireMode Mode = FireMode.Direct;
        public float Damage = 25f;
        public float RangeMin = 0f, RangeMax = 60f;
        public float RoundsPerSecond = 0.8f;
        public int BurstRounds = 1;
        public int MagazineRounds = 0;
        public float ReloadSeconds = 0f;
        [Range(0f, 1f)] public float Accuracy = 0.6f;
        public float PenetrationMm = 0f;
        public float BlastRadius = 0f;
        public float SuppressionPerShot = 4f;
        public float MuzzleVelocity = 0f;
        public byte CraterRadiusDm = 0;
        public bool SetsBurning;

        public WeaponStats ToStats() => new WeaponStats
        {
            Id = Id, Mode = Mode, Damage = Damage, RangeMin = RangeMin, RangeMax = RangeMax, RoundsPerSecond = RoundsPerSecond,
            BurstRounds = BurstRounds, MagazineRounds = MagazineRounds, ReloadSeconds = ReloadSeconds, Accuracy = Accuracy,
            PenetrationMm = PenetrationMm, BlastRadius = BlastRadius, SuppressionPerShot = SuppressionPerShot,
            MuzzleVelocity = MuzzleVelocity, CraterRadiusDm = CraterRadiusDm, SetsBurning = SetsBurning,
        };
    }

    [CreateAssetMenu(menuName = "TW/Unit Definition")]
    public sealed class UnitDefinition : ScriptableObject
    {
        public short Id;
        public string DisplayName;
        public Faction Faction;
        public UnitClass Class;
        public int Cost = 25;
        public float Hp = 100f;
        public float Speed = 3f;
        public WeaponDefinition PrimaryWeapon;
        public WeaponDefinition SecondaryWeapon;
        public float GrenadeRange = 0f;
        public int DeployCooldownTicks = 0;
        public float ArmorFrontMm, ArmorSideMm, ArmorRearMm, ArmorTopMm;
        public float AuraRadius = 0f;
        public float ShieldArcHalfWidthDeg = 0f;
        public bool CanEnterTrench = true;
        public bool IsVehicle, IsEmplacement, ImmuneToPinned;
        public float TrenchHpBonus = 0f, TrenchAccuracyBonus = 0f, TrenchRangeBonus = 0f;
        public byte TargetPriorityProfile = 0;
        [Header("Presentation")]
        public string VatArchetype = "infantry_rifle";
        public string MeshKey;

        public UnitStats ToStats() => new UnitStats
        {
            Id = Id, Class = Class, Cost = Cost, Hp = Hp, Speed = Speed,
            PrimaryWeapon = PrimaryWeapon != null ? PrimaryWeapon.Id : (short)-1,
            SecondaryWeapon = SecondaryWeapon != null ? SecondaryWeapon.Id : (short)-1,
            GrenadeRange = GrenadeRange, DeployCooldownTicks = DeployCooldownTicks,
            Armor = new ArmorProfile { FrontMm = ArmorFrontMm, SideMm = ArmorSideMm, RearMm = ArmorRearMm, TopMm = ArmorTopMm },
            AuraRadius = AuraRadius, ShieldArcHalfWidth = ShieldArcHalfWidthDeg * Mathf.Deg2Rad, CanEnterTrench = CanEnterTrench,
            IsVehicle = IsVehicle, IsEmplacement = IsEmplacement, ImmuneToPinned = ImmuneToPinned,
            TrenchHpBonus = TrenchHpBonus, TrenchAccuracyBonus = TrenchAccuracyBonus, TrenchRangeBonus = TrenchRangeBonus,
            TargetPriorityProfile = TargetPriorityProfile,
        };
    }

    [CreateAssetMenu(menuName = "TW/Ability Definition")]
    public sealed class AbilityDefinition : ScriptableObject
    {
        public OffMapAbilityId Id;
        public string DisplayName;
        public int Cost = 150;
        public int CooldownTicks = 1200;
        public int WarmupTicks = 80;
        public AbilityTargetMode Target = AbilityTargetMode.Area;
        public float Radius = 25f, Length = 0f;
        public int Shells = 12; public float ShellDamage = 150f, ShellRadius = 8f; public int SpreadTicks = 120;
        public float Concentration = 0f; public int PersistTicks = 0;
        public bool BreachesWire, CollapsesTrench, DestroysBunker;

        public AbilityStats ToStats() => new AbilityStats
        {
            Id = Id, Cost = Cost, CooldownTicks = CooldownTicks, WarmupTicks = WarmupTicks, Target = Target, Radius = Radius, Length = Length,
            Shells = Shells, ShellDamage = ShellDamage, ShellRadius = ShellRadius, SpreadTicks = SpreadTicks, Concentration = Concentration,
            PersistTicks = PersistTicks, BreachesWire = BreachesWire, CollapsesTrench = CollapsesTrench, DestroysBunker = DestroysBunker,
        };
    }

    [CreateAssetMenu(menuName = "TW/Faction Definition")]
    public sealed class FactionDefinition : ScriptableObject
    {
        public Faction Faction;
        public string DisplayName;
        [Tooltip("Exactly five: Rifleman, Assault, Machinegunner, Special, Vehicle")]
        public UnitDefinition[] DefaultSlots = new UnitDefinition[5];
        public List<UnitDefinition> AlternateSpecials = new List<UnitDefinition>();
        public List<UnitDefinition> AlternateVehicles = new List<UnitDefinition>();
        public List<string> UniformSkins = new List<string>();
    }

    [System.Serializable]
    public struct MissionTriggerAuthoring
    {
        public short Id;
        public TriggerCondition Condition;
        public int CondA, CondB;
        public byte CondTeam;
        public int DelayTicks;
        public bool Once;
        public MissionActionAuthoring[] Actions;
    }

    [System.Serializable]
    public struct MissionActionAuthoring
    {
        public TriggerAction Kind;
        public int A, B;
        public Vector3 Pos;
        public Vector2 Vec;
    }

    [System.Serializable]
    public struct WaveEntryAuthoring { public UnitDefinition Unit; public int Count; public byte EntryPoint; public byte Order; }

    [System.Serializable]
    public struct WaveTableAuthoring { public short Id; public string Name; public WaveEntryAuthoring[] Entries; public int IntervalTicks; }

    [CreateAssetMenu(menuName = "TW/Mission Definition")]
    public sealed class MissionDefinition : ScriptableObject
    {
        public string Title;
        [TextArea] public string Briefing;
        public int MapId = 1;
        public FactionDefinition PlayerFaction, EnemyFaction;
        public UnitDefinition[] PlayerSlotOverrides = new UnitDefinition[5];
        public bool[] SlotUnlockedAtStart = { true, true, true, true, true };
        public AbilityDefinition[] Abilities;
        public bool[] AbilityUnlockedAtStart;
        public int StartingSilver = 120;
        public float IncomePerSecond = 1.2f;
        public byte Difficulty;
        public WinRule Win; public int WinParam;
        public LoseRule Lose; public int LoseParam;
        public WaveTableAuthoring[] Waves;
        public MissionTriggerAuthoring[] Triggers;
        public string[] Dialogue;
        public int GoldNormal = 25, GoldHard = 40, GoldFinale = 75;
    }
}
